Require dmidecode in spec file
SUSE-Enceladus/supportutils-plugin-suse-public-cloud pull request #10
Opened 2023-04-06 08:25 UTC by jgleissner

Require dmidecode as it is used to determine the framework.

2023-04-06 12:32 UTC, smarlowucf approved these changes

2023-04-06 13:19 UTC, rjschwei requested changes

2023-04-06 13:37 UTC, jgleissner commented on supportutils-plugin-suse-public-cloud.spec
> +Requires:       dmidecode
It's also on aarch64, so from public cloud PoV we're good. But it's not on s390 for instance, so it should still have an appropriate %ifarch. I'll add one.

2023-04-07 13:01 UTC, rjschwei commented on supportutils-plugin-suse-public-cloud.spec
> +Requires:       dmidecode
ia64? Isn't that Itanic aka Itanium? Haven't seen that in forever. Hopefully no one gets any crazy ideas.

2023-04-07 13:01 UTC, rjschwei approved these changes

2023-04-07 13:01 UTC, merged